
services:
  emqx1:
    image: emqx
    container_name: emqx
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    volumes:
      - .emqx/data:/opt/emqx/data \
      - .emqx/log:/opt/emqx/log \
  mqttx-web:
    image: emqx/mqttx-web
    container_name:  mqttxweb
    networks:
      emqx-bridge:
        aliases:
        - mqttxweb
    ports:
      - 80:80


networks:
  emqx-bridge:
    driver: bridge